topics:
  left_image:
    name: "/stereo/left/image_raw/compressed"
    type: "sensor_msgs/CompressedImage"
  right_image:
    name: "/stereo/right/image_raw/compressed"
    type: "sensor_msgs/CompressedImage"
  os1:
    name: "/ouster/points"
    type: "sensor_msgs/PointCloud2"
houghStrategy: "cuda"
debugMode: 1 # 0 is no debug, -> increases verbosity
frameWidth: 960
frameHeight: 600
laneWidth: 4 # meters
numLanes:  6 # number of lane lines
laneForwardMin: 5 # minimum start distnace ahead of the car to search for lanes
laneForwardMax: 10 # maximum distance ahead of the car to search for lanes